_target_: mbrl.models.GaussianMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 7
hid_size: ${overrides.model_hidden_size}
deterministic: false
propagation_method: random_model
learn_logvar_bounds: false  # so far this works better
minimum_variance_exponent: ${overrides.minimum_variance_exponent}
#Recursive instantiation not working with new hydra version why #TODO
#Workaround now is to set SiLU as standard in GaussianMLP
